name: surf_practice_chat_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  geolocator: ^9.0.2
  image_picker: ^0.8.6+1
  intl: ^0.18.0
  liquid_pull_to_refresh: ^3.0.1
  maps_launcher: ^2.0.1
  shared_preferences: ^2.0.17
  surf_study_jam: ^0.2.0+1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

